version: '3'

services:
  redis:
    image: redis
    command: redis-server
    ports:
      - '6379:6379'
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
#  worker_channels:
#    build: .
#    command: python manage.py runworker application
#    volumes:
#      - ./app:/app
#    links:
#      - redis
  channels:
    build: .
    command: daphne -p 8001 ChatSite.asgi:application
    volumes:
      - ./app:/app
    ports:
      - "8001:8001"
    links:
      - redis